[[main]]
name = 'Hem'
pageRef = '/'
weight = 10

[[main]]
name = 'Produkter'
pageRef = 'products'
weight = 20

[[main]]
name = 'Manualer'
pageRef = 'manuals'
weight = 30

[[main]]
name = 'Användningsområden'
pageRef = 'applications'
weight = 40

[[main]]
name = 'Om oss'
pageRef = 'about'
weight = 50
